### ISSUE TITLE
Data Transfer experiments stuck at subexperiment 0

### ISSUE THREAD

**Issue by varungohil** [ease-lab/STeLLAR#144]
Hello, 

I am reproducing the data transfer results showed in the STeLLAR paper using vHive.
I have setup vHive on cloud lab using the provided profile.

To run the experiments I ran the commands given here: https://github.com/ease-lab/STeLLAR/wiki/vHive-Benchmarking

On running the command for inline data transfer, I get the output shown below. The experiment has been running for multiple hours now and is stuck at subexperiment 0. 
![image](https://user-images.githubusercontent.com/25960514/157258698-1831160e-6c12-46ef-b3bc-217818cda69e.png)

I checked and confirmed that all pods are up and running. All kn services deployed by deploy_functions script are also up
![image](https://user-images.githubusercontent.com/25960514/157259068-d606071c-3de1-4d0a-8446-1670e3533a48.png)

The warm.json file is the same as the one in the repo. 
I have modified the vHive.json file in endpoints/vhive to include the correct Gateway ID. Specifically I have replaced 
**producer.default.192.168.1.240.nip.io:80** and **consumer.default.192.168.1.240.nip.io:80** with **producer.default.192.168.1.240.sslip.io:50051**

**Comment by ustiugov** [comment]
@amariucaitheodor could you please take a look? the problem might be on the vHive side but stellar should have a timeout instead of hanging indefinitely.

**Comment by amariucaitheodor** [comment]
Hello @varungohil, could you please provide the logs of **producer.default.192.168.1.240.sslip.io:50051**? 
Also, would you try deploying **producer.default.192.168.1.240.sslip.io:50051** and **consumer.default.192.168.1.240.sslip.io:50051** and running again (+logs if it hangs again)?

**Comment by varungohil** [comment]
Hey @amariucaitheodor, I am new to these tools. Can you tell me how to access the logs? Thanks.

**Comment by amariucaitheodor** [comment]
If I remember correctly, knative uses kubernetes under the hood to spawn pods as requests for serverless computation keep coming in. Since the code still runs in containers, to get the logs, I think `kubectl get pods` followed by `kubectl logs my-pod` should do the trick.

**Comment by varungohil** [comment]
Hey, the image shows the output that i get on running `kubectl get pods -A`. There is no producer pod
![image](https://user-images.githubusercontent.com/25960514/157895160-66329002-9052-4336-a796-b00c3bb8ec98.png)

**Comment by aditya2803** [comment]
Hi, was this fixed ? I am running into the same issue

**Comment by ustiugov** [comment]
@aditya2803 could you please provide your logs, as specified by Theodor (the key maintainer) above. he will try to get back to you as soon as possible

**Comment by aditya2803** [comment]
Hi @ustiugov @amariucaitheodor the logs are exactly what @varungohil pasted [here](https://github.com/ease-lab/STeLLAR/issues/144#issue-1162740677). No new deployment pods get created, because I suspect the invocation does not go through at all. Let me know if you need anything else.

**Comment by ustiugov** [comment]
the port should :80 (this is the one for the queue proxy to listen to) not 50051 (the user containers listens to).

**Comment by aditya2803** [comment]
Thanks @ustiugov, the problem was probably with the port being put as 50051. With the port as 80, the experiment is running properly. This can be closed now I guess. Thanks again.
